Cities = {
     'sz': '深圳',
     'gz': '广州',
     'sh': '上海',
     'bj': '北京',
}

DM = {'深圳': ['光明区', '南山区', '坪山区', '大鹏新区', '宝安区', '福田区', '罗湖区', '龙华区', '盐田区','龙岗区'] ,
      '上海': ['嘉定', '奉贤', '宝山', '崇明', '徐汇', '普陀', '杨浦', '松江', '浦东', '虹口', '金山', '长宁', '闵行', '青浦', '静安', '黄浦'],
      '嘉定': ['丰庄', '华亭', '南翔', '嘉定新城', '嘉定老城', '安亭', '徐行', '新成路', '江桥', '菊园新区'],
      '奉贤': ['庄行', '海湾', '西渡'],
      '宝山': ['上大', '共康', '大场镇', '月浦', '淞南', '淞宝', '罗店', '罗泾', '通河', '高境'],
      '崇明': ['崇明其它'] ,
      '徐汇': ['万体馆', '华东理工', '华泾', '康健', '建国西路', '徐家汇', '徐汇滨江', '斜土路', '植物园', '长桥', '龙华'],
      '普陀': ['光新', '曹杨', '武宁', '甘泉宜川', '真光', '真如', '长寿路', '长征', '长风'],
      '杨浦': ['东外滩', '中原', '周家嘴路', '控江路', '新江湾城', '鞍山', '高境'],
      '松江': ['九亭', '佘山', '新桥', '松江大学城', '松江新城', '松江老城', '泗泾', '莘闵别墅', '车墩'],
      '浦东': ['万祥镇', '三林', '外高桥', '川沙', '康桥', '御桥', '惠南', '曹路', '杨东', '洋泾', '源深', '碧云', '联洋', '航头', '花木', '陆家嘴'],
      '虹口': ['临平路', '北外滩', '四川北路', '鲁迅公园'],
      '金山': ['亭林', '张堰', '金山'],
      '长宁': ['中山公园', '仙霞', '天山', '新华路', '虹桥', '西郊', '镇宁路'],
      '闵行': ['华漕', '静安新城'],
      '青浦': ['盈浦'],
      '静安': ['南京西路', '彭浦', '曹家渡', '永和', '江宁路', '西藏北路', '阳城'],
      '黄浦': ['世博滨江', '五里桥', '人民广场', '打浦桥', '淮海中路', '老西门', '蓬莱公园', '黄浦滨江'],
      '光明区': ['公明'],
      '南山区': ['前海', '华侨城', '南头', '南山中心', '后海', '深圳湾', '白石洲', '科技园', '红树湾', '西丽'],

      '坪山区': ['坪山'],
      '大鹏新区': ['大鹏半岛'],

      '宝安区': ['宝安中心', '新安', '松岗', '桃源居', '沙井', '翻身', '西乡'],
      '福田区': ['上下沙', '上步', '华强南', '园岭', '新洲', '沙尾', '百花', '皇岗', '石厦', '福田中心', '福田保税区', '竹子林', '莲花', '赤尾', '车公庙', '香梅北', '香蜜湖', '黄木岗'],
      '罗湖区': ['万象城', '东门', '布心', '新秀', '洪湖', '清水河', '百仕达', '笋岗', '罗湖口岸', '螺岭', '黄贝岭'],

      '龙华区': ['上塘', '梅林关', '民治', '红山', '龙华新区'],

}

ZH_EN={
     'wantiguan': '万体馆',
     'wanxiangzhen': '万祥镇',
     'wanxiangcheng': '万象城',
     'sanlin': '三林',
     'shangxiasha':' 上下沙',
     'shangtang': '上塘',
     'shangda': '上大',
     'shangbu': '上步',
     'shibobinjiang': '世博滨江',
     'dongwaitan': '东外滩',
     'dongmen': '东门',
     'zhongyuan': '中原',
     'zhongshangongyuan': '中山公园',
     'fengzhuang':'丰庄',
     'linpinglu':'临平路',
     'jiuting':'九亭',
     'wuliqiao':'五里桥',
     'tinglin':'亭林',
     'renminguangchang':'人民广场',
     'xianxia':'仙霞',
     'sheshan':'佘山',
     'guangxin':'光新',
     'gongming':'公明',
     'gongkang':'共康',
     'qianhai':'前海',
     'beiwaitan':'北外滩',
     'huadongligong':'华东理工',
     'huating':'华亭',
     'huaqiaocheng':'华侨城',
     'huaqiangnan':'华强南',
     'huajing':'华泾',
     'huacao':'华漕',
     'nanjingxilu':'南京西路',
     'nantou':'南头',
     'nanshanzhongxin':'南山中心',
     'nanxiang':'南翔',
     'zhoujiazuilu':'周家嘴路',
     'jiadingxincheng':'嘉定新城',
     'jiadinglaocheng':'嘉定老城',
     'sichuanbeilu':'四川北路',
     'yuanling':'园岭',
     'pingshan':'坪山',
     'waigaoqiao':'外高桥',
     'dachangzhen':'大场镇',
     'dapengbandao':'大鹏半岛',
     'tianshan':'天山',
     'anting':'安亭',
     'baoanzhongxin':'宝安中心',
     'chongmingqita':'崇明其它',
     'chuansha':'川沙',
     'buxin':'布心',
     'zhuangxing':'庄行',
     'kangjian':'康健',
     'kangqiao':'康桥',
     'jianguoxilu':'建国西路',
     'zhangyan':'张堰',
     'pengpu':'彭浦',
     'xujiahui':'徐家汇',
     'xuxing':'徐行',
     'yuqiao':'御桥',
     'huinan':'惠南',
     'dapuqiao':'打浦桥',
     'kongjianglu':'控江路',
     'xietulu':'斜土路',
     'xinhualu':'新华路',
     'xinan':'新安',
     'xinchenglu':'新成路',
     'xinqiao':'新桥',
     'xinjiangwancheng':'新江湾城',
     'xinzhou':'新洲',
     'xinxiu':'新秀',
     'caojiadu':'曹家渡',
     'caoyang':'曹杨',
     'caolu':'曹路',
     'yuepu':'月浦',
     'yangdong':'杨东',
     'songgang':'松岗',
     'songjiangdaxuecheng':'松江大学城',
     'songjiangxincheng':'松江新城',
     'songjianglaocheng':'松江老城',
     'taoyuanju':'桃源居',
     'zhiwuyuan':'植物园',
     'wuning':'武宁',
     'minzhi':'民治',
     'yonghe':'永和',
     'jiangninglu':'江宁路',
     'jiangqiao':'江桥',
     'shajing':'沙井',
     'shawei':'沙尾',
     'yangjing':'洋泾',
     'honghu':'洪湖',
     'haiwan':'海湾',
     'songnan':'淞南',
     'songbao':'淞宝',
     'huaihaizhonglu':'淮海中路',
     'shenzhenwan':'深圳湾',
     'qingshuihe':'清水河',
     'yuanshen':'源深',
     'ganquanyichuan':'甘泉宜川',
     'baishizhou':'白石洲',
     'baishida':'百仕达',
     'baihua':'百花',
     'huanggang':'皇岗',
     'yingpu':'盈浦',
     'zhenguang':'真光',
     'zhenru':'真如',
     'shisha':'石厦',
     'biyun':'碧云',
     'futianzhongxin':'福田中心',
     'futianbaoshuiqu':'福田保税区',
     'kejiyuan':'科技园',
     'zhuzilin':'竹子林',
     'sungang':'笋岗',
     'hongshan':'红山',
     'hongshuwan':'红树湾',
     'luodian':'罗店',
     'luohukouan':'罗湖口岸',
     'fanshen':'翻身',
     'laoximen':'老西门',
     'lianyang':'联洋',
     'hangtou':'航头',
     'huamu':'花木',
     'shenminbieshu':'莘闵别墅',
     'lianhua':'莲花',
     'juyuanxinqu':'菊园新区',
     'penglaigongyuan':'蓬莱公园',
     'hongqiao':'虹桥',
     'luoling':'螺岭',
     'xili':'西丽',
     'xixiang':'西乡',
     'xidu':'西渡',
     'xizangbeilu':'西藏北路',
     'xijiao':'西郊',
     'chiwei':'赤尾',
     'chegongmiao':'车公庙',
     'chedun':'车墩',
     'tonghe':'通河',
     'jinshan':'金山',
     'zhenninglu':'镇宁路',
     'changshoulu':'长寿路',
     'changzheng':'长征',
     'zhangqiao':'长桥',
     'zhangfeng':'长风',
     'yangcheng':'阳城',
     'lujiazui':'陆家嘴',
     'anshan':'鞍山',
     'xiangmeibei':'香梅北',
     'xiangmihu':'香蜜湖',
     'luxungongyuan':'鲁迅公园',
     'huangmugang':'黄木岗',
     'huangpubinjiang':'黄浦滨江',
     'huangbeiling':'黄贝岭',
     'longhua':'龙华',
     'longhuaxinqu':'龙华新区',
     'guangmingqu':'光明区',
     'nanshanqu':'南山区',
     'pingshanqu':'坪山区',
     'dapengxinqu':'大鹏新区',
     'baoanqu':'宝安区',
     'futianqu':'福田区',
     'luohuqu':'罗湖区',
     'longhuaqu':'龙华区',
     'jiading':'嘉定',
     'fengxian':'奉贤',
     'baoshan':'宝山',
     'chongming':'崇明',
     'xuhui':'徐汇',
     'putuo':'普陀',
     'yangpu':'杨浦',
     'songjiang':'松江',
     'pudong':'浦东',
     'hongkou':'虹口',
     'jinshan':'金山',
     'zhangning':'长宁',
     'minxing':'闵行',
     'qingpu':'青浦',
     'jingan':'静安',
     'huangpu':'黄浦',


}
